# Generated by Django 5.1.2 on 2025-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPost_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='is_accepted',
            field=models.BooleanField(default=0),
        ),
    ]
