# Generated by Django 5.1.2 on 2025-01-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPost_App', '0003_alter_applied_job_alter_jobpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='description',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='applied',
            name='resume',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
    ]
